### ISSUE TITLE
Can I Add Chess Games With full Chess Match Analysis

### ISSUE THREAD

**Issue by guptavaibhav159** [alecho/chex#30]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alecho** [comment]
Hey thanks for the question! This doesn't seem like a feature request so I'll edit the labels as such.

This project is not a chess engine and therefore doesn't play or make judgments on chess games. That said there is basic UCI support with the `Chex.Engine` module that can open a Port to a chess engine (tested with stockfish for now) and send state (as FEN) and ask for the best move. You can see this in action at another project of mine that uses Chex. It's currently on the latest release (0.1.2) but I hope to have 0.2.0 out soon. I also home to update live_chess to use Chex 0.2.0+ but the multitude of changes from 0.1.2.to 0.2.0 will made that a larger undertaking.

In the future we could do some analysis using an outside engine on a game but we'd need PGN support which is an open issue if you'd like to take a look: #21
